# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Charticulator
email: charticulator@microsoft.com
description: > # this means to ignore newlines until "baseurl:"
  Charticulator's Website
baseurl: "" # the subpath of your site, e.g. /blog
instrumentation_key: ""
url: "https://charticulator.com" # the base hostname & protocol for your site, e.g. http://example.com

# Enable CDN when deploying the site.
cdn_enabled: true
# Configure the CDN endpoint
cdn_prefix: "https://charticulator.azureedge.net"

# Build settings
markdown: kramdown
theme: minima

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - tutorials/viewer/

collections:
  gallery:
    output: true
  tutorials:
    output: true
  docs:
    output: true

defaults:
  - scope:
      path: ""
      type: gallery
    values:
      layout: gallery
  - scope:
      path: ""
      type: tutorials
    values:
      layout: tutorials
  - scope:
      path: ""
      type: docs
    values:
      layout: docs
